[package]
name = "fluor"
version = "0.1.0"
authors = ["Richard do Nascimento Fagundes <richardnas_@outlook.com>"]
edition = "2018"

[dependencies]
hyper = "0.12"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
http = "0.1"
futures = "0.1"
base64 = "0.10"